name: "Infra template test - $(Build.SourceBranchName)"

trigger: none

pool:
  vmImage: ubuntu-latest

resources:
  repositories:
    - repository: InfraRepo
      type: github
      name: qlap04/goat-ticket-infra
      ref: dev
      endpoint: qlap04

variables:
  - group: goat-ticket-secrets-dev

stages:
  - stage: InfraDev
    displayName: "Deploy infrastructure to dev"
    jobs:
      - template: deploy/templates/deploy-infra-jobs.yml@InfraRepo
        parameters:
          environment: dev
          target: dev
