name: "Demo Pipeline - Deploy Infra from App Repo"

trigger: none

pool:
  vmImage: "ubuntu-latest"

resources:
  repositories:
    - repository: InfraRepo
      type: github
      name: qlap04/goat-ticket-infra
      ref: dev
      endpoint: "qlap04"

variables:
  - group: goat-ticket-secrets-dev

steps:
  - checkout: self
  - checkout: InfraRepo

  # ===== Infra deploy
  - template: deploy/templates/deploy-infra.yml@InfraRepo
    parameters:
      environment: dev

  - template: deploy/templates/demo.yml

  - script: echo "App-specific deploy steps continue here..."
    displayName: "Continue with app deployment"
