name: "Demo Pipeline - Deploy Infra from App Repo"

trigger: none

pool:
  vmImage: "ubuntu-latest"

resources:
  repositories:
    - repository: InfraRepo
      type: github
      name: qlap04/goat-ticket-infra
      ref: dev
      endpoint: "qlap04"

variables:
  - group: goat-ticket-secrets-dev

steps:
  - checkout: self
  - checkout: InfraRepo

  - script: |
      echo "=== Pipeline.Workspace ==="
      ls -la $(Pipeline.Workspace)
      echo ""
      echo "=== Build.SourcesDirectory ==="
      ls -la $(Build.SourcesDirectory)
      echo ""
      echo "=== Tìm main.bicep ở đâu ==="
      find $(Pipeline.Workspace) -name "main.bicep" 2>/dev/null