using Azure.Storage.Blobs;
using GoatTicket.Domain.Entities;
using GoatTicket.Infrastructure.Repositories;
using GoatTicket.Shared.Messages;
using GoatTicket.Shared.Ticketing;
using MailKit.Net.Smtp;
using MailKit.Security;
using Microsoft.Azure.Functions.Worker;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using MimeKit;
using QRCoder;
using QuestPDF.Fluent;
using QuestPDF.Helpers;

namespace GoatTicket.Functions;

/// <summary>
/// Queue trigger on `order-created`. Idempotent per contracts/queue-messages.md's consumer
/// contract and research.md §9: every step is safe to repeat, because a redelivered message
/// (host.json `maxDequeueCount`) re-runs this Function from the top. Exhausted retries fall
/// through to `order-created-poison`, handled by <see cref="OrderFulfillmentPoisonHandler"/>.
/// </summary>
public class OrderFulfillmentProcessor(
    OrderRepository orderRepository,
    UserRepository userRepository,
    BlobServiceClient blobServiceClient,
    TicketQrSigner ticketQrSigner,
    IConfiguration configuration,
    ILogger<OrderFulfillmentProcessor> logger)
{
    [Function(nameof(OrderFulfillmentProcessor))]
    public async Task RunAsync([QueueTrigger("order-created", Connection = "QueueStorage")] OrderCreatedQueueMessage message)
    {
        var order = await orderRepository.GetTrackedByIdAsync(message.OrderId);
        if (order is null)
        {
            logger.LogWarning("OrderFulfillmentProcessor: order {OrderId} not found.", message.OrderId);
            return;
        }

        var containerName = configuration["Storage:TicketsContainerName"] ?? "tickets";
        var containerClient = blobServiceClient.GetBlobContainerClient(containerName);
        await containerClient.CreateIfNotExistsAsync();

        var attachments = new List<(string FileName, byte[] Bytes)>();

        foreach (var item in order.Items)
        {
            if (item.TicketBlobUrl is null)
            {
                // Not yet generated (first attempt, or a prior attempt failed before this item) — generate it now.
                var (token, jti) = ticketQrSigner.Sign(order.Id, item.SeatId);
                var pdfBytes = GenerateTicketPdf(order, item, token);

                var blobName = $"{order.Id}/{item.SeatId}.pdf";
                var blobClient = containerClient.GetBlobClient(blobName);
                await using (var stream = new MemoryStream(pdfBytes))
                {
                    await blobClient.UploadAsync(stream, overwrite: true);
                }

                item.TicketBlobUrl = blobClient.Uri.ToString();
                item.QrPayloadJti = jti;

                attachments.Add(($"ticket-seat-{item.SeatId}.pdf", pdfBytes));
            }
            // else: already generated by a prior attempt (idempotency, research.md §9) — skip regeneration.
        }

        await orderRepository.SaveAsync(order);

        if (order.EmailSentAtUtc is null)
        {
            // Re-download any tickets generated in an earlier attempt so the email always
            // includes every item, even on a retry that only had new items to generate above.
            if (attachments.Count < order.Items.Count)
            {
                attachments.Clear();
                foreach (var item in order.Items)
                {
                    var blobClient = containerClient.GetBlobClient(new Uri(item.TicketBlobUrl!).AbsolutePath.TrimStart('/').Replace($"{containerName}/", string.Empty));
                    var download = await blobClient.DownloadContentAsync();
                    attachments.Add(($"ticket-seat-{item.SeatId}.pdf", download.Value.Content.ToArray()));
                }
            }

            var user = await userRepository.GetByIdAsync(order.UserId);
            if (user is not null)
            {
                await SendConfirmationEmailAsync(user.Email, order, attachments);
            }
            else
            {
                logger.LogWarning("OrderFulfillmentProcessor: user {UserId} not found for order {OrderId}; email not sent.", order.UserId, order.Id);
            }

            order.EmailSentAtUtc = DateTime.UtcNow; // FR-014, idempotency guard (research.md §9)
            await orderRepository.SaveAsync(order);
        }
        // else: email already sent by a prior attempt — do not send again.

        order.Status = OrderStatus.Fulfilled;
        await orderRepository.SaveAsync(order);

        logger.LogInformation("Order {OrderId} fulfilled: {ItemCount} ticket(s).", order.Id, order.Items.Count);
    }

    private static byte[] GenerateTicketPdf(Order order, OrderItem item, string qrToken)
    {
        var qrGenerator = new QRCodeGenerator();
        var qrCodeData = qrGenerator.CreateQrCode(qrToken, QRCodeGenerator.ECCLevel.Q);
        var qrPng = new PngByteQRCode(qrCodeData).GetGraphic(20);

        return Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Size(PageSizes.A5);
                page.Margin(30);
                page.Content().Column(column =>
                {
                    column.Spacing(10);
                    column.Item().Text("The 1000th Goal Ceremony").FontSize(18).Bold();
                    column.Item().Text($"Order: {order.Id}");
                    column.Item().Text($"Seat: {item.SeatId} ({item.Tier})");
                    column.Item().Text($"Price: {item.Price:C}");
                    column.Item().Image(qrPng);
                    column.Item().Text("Present this QR code at the stadium gate.").FontSize(10);
                });
            });
        }).GeneratePdf();
    }

    private async Task SendConfirmationEmailAsync(string toEmail, Order order, List<(string FileName, byte[] Bytes)> attachments)
    {
        var message = new MimeMessage();
        message.From.Add(MailboxAddress.Parse(configuration["Email:FromAddress"] ?? "tickets@goat-ticket.local"));
        message.To.Add(MailboxAddress.Parse(toEmail));
        message.Subject = "Your e-ticket(s) for The 1000th Goal Ceremony";

        var bodyBuilder = new BodyBuilder
        {
            TextBody = $"Thank you for your order ({order.Id}). Your {attachments.Count} e-ticket(s) are attached."
        };

        foreach (var (fileName, bytes) in attachments)
        {
            bodyBuilder.Attachments.Add(fileName, bytes, ContentType.Parse("application/pdf"));
        }

        message.Body = bodyBuilder.ToMessageBody();

        using var smtpClient = new SmtpClient();
        var host = configuration["Email:SmtpHost"] ?? "localhost";
        var port = int.Parse(configuration["Email:SmtpPort"] ?? "1025");
        await smtpClient.ConnectAsync(host, port, SecureSocketOptions.None);
        await smtpClient.SendAsync(message);
        await smtpClient.DisconnectAsync(quit: true);
    }
}
