parameters:
  - name: hotfixEnvironment
    type: string
    values:
      - dev
      - sit
      - uat
      - preprod

  - name: deployInfraAll
    type: boolean

  - name: createKeyVaultSecrets
    type: boolean

  - name: environments
    type: object
    default:
      - environment: dev
        environmentName: goat-dev
        previousStage: Build
        branchMatch: "eq(variables['Build.SourceBranch'], 'refs/heads/develop')"
        deploymentSlot: none
      - environment: sit
        environmentName: goat-sit
        previousStage: Deploy_dev
        branchMatch: "startsWith(variables['Build.SourceBranch'], 'refs/heads/release/')"
        deploymentSlot: none
      - environment: uat
        environmentName: goat-uat
        previousStage: Deploy_sit
        branchMatch: "startsWith(variables['Build.SourceBranch'], 'refs/heads/release/')"
        deploymentSlot: none
      - environment: preprod
        environmentName: goat-preprod
        previousStage: Deploy_uat
        branchMatch: "eq(variables['Build.SourceBranch'], 'refs/heads/main')"
        deploymentSlot: none
      - environment: prod
        environmentName: goat-prod
        previousStage: Deploy_preprod
        branchMatch: "eq(variables['Build.SourceBranch'], 'refs/heads/main')"
        deploymentSlot: none

stages:
  - ${{ each env in parameters.environments }}:
      - template: deploy-env-stage.yml
        parameters:
          environment: ${{ env.environment }}
          environmentName: ${{ env.environmentName }}
          previousStage: ${{ env.previousStage }}
          branchMatch: ${{ env.branchMatch }}
          deploymentSlot: ${{ env.deploymentSlot }}
          hotfixEnvironment: ${{ parameters.hotfixEnvironment }}
          deployInfraAll: ${{ parameters.deployInfraAll }}
          createKeyVaultSecrets: ${{ parameters.createKeyVaultSecrets }}
